[workspace]
resolver = "2"

members = [
    "libprocess",
    "libprocess-builder",
]

exclude = [ "target" ]

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.release]
opt-level = 3