[package]
name = "libprocess"
version = "0.1.0"
edition = "2021"

[lib]
name = "Process"
crate-type = ["cdylib"]

[dependencies]
value-box = "1.1"
string-box = "1.1"
array-box = "1.0"
libc = "0.2"
log = "0.4"
env_logger = "0.7"
encoding_rs = "0.8"